### ISSUE TITLE
1-b = "c"   ParseError

### ISSUE THREAD

**Issue by Axel2** [fbernier/tomlrb#8]
`1-b = "c"`

gives Tomlrb::ParseError:

```
C:/Users.../tomlrb-1.2.3/lib/tomlrb.rb:25:in `rescue in parse':  (Tomlrb::ParseError)
parse error on value "-b" (IDENTIFIER)
	from C:/.../tomlrb-1.2.3/lib/tomlrb.rb:22:in `parse'
	from C:/.../tomlrb-1.2.3/lib/tomlrb.rb:38:in `load_file'
	from C:/.../tmp001.rb:4:in `<main>'
```

According to https://github.com/toml-lang/toml:
"Bare keys may only contain letters, numbers, underscores, and dashes (A-Za-z0-9_-)."
it should work, I think.

`a-b = "c"`

works as expected.

Using:
* Windows7
* ruby-2.3.3-i386-mingw32
* gems/tomlrb-1.2.3

Axel

**Comment by fbernier** [comment]
This is indeed probably a bug. I'll look into it but meanwhile you can quote the key:

```
"1-b" = "c"
```

**Comment by oblueONI** [comment]
```
[caps]
platform-Name = “ios”
app = “./UICatalog-iphonesimulator.app”
```

I see the same error when I try to start console for appium testing(http://appium.io/slate/en/tutorial/ios.html?java#starting-the-console):

```
/.../rvm/gems/ruby-2.4.0/gems/tomlrb-1.2.3/lib/tomlrb.rb:25:in `rescue in parse':  (Tomlrb::ParseError)
parse error on value "“" (error)
	from /.../.rvm/gems/ruby-2.4.0/gems/tomlrb-1.2.3/lib/tomlrb.rb:22:in `parse'
	from /../.rvm/gems/ruby-2.4.0/gems/tomlrb-1.2.3/lib/tomlrb.rb:38:in `load_file'
	from /.../.rvm/gems/ruby-2.4.0/gems/appium_lib-8.2.1/lib/appium_lib/driver.rb:86:in `load_settings'
	from /.../.rvm/gems/ruby-2.4.0/gems/appium_console-2.1.0/lib/appium_console.rb:19:in `block in setup'
	from /.../.rvm/gems/ruby-2.4.0/gems/appium_console-2.1.0/lib/appium_console.rb:41:in `start'
	from /.../.rvm/gems/ruby-2.4.0/gems/appium_console-2.1.0/lib/cli.rb:72:in `init'
	from /.../.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /.../.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /.../.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /.../.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /.../.rvm/gems/ruby-2.4.0/gems/appium_console-2.1.0/lib/cli.rb:81:in `<top (required)>'
	from /.../.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /.../.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /.../.rvm/gems/ruby-2.4.0/gems/appium_console-2.1.0/bin/arc:3:in `<top (required)>'
	from /.../.rvm/gems/ruby-2.4.0/bin/arc:22:in `load'
	from /.../.rvm/gems/ruby-2.4.0/bin/arc:22:in `<main>'
	from /.../.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /.../.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

Using:
    OSX 10.11.6 (el capitan)

**Comment by fbernier** [comment]
@oblueONI you are using curly double quotes `“ ”` while you need to use straight ones `" "`

**Comment by oblueONI** [comment]
It works now..Thanks!
